"""add token type

Revision ID: 1b814d2ebbd8
Revises: a49d6e32b01d
Create Date: 2025-07-20 21:30:33.548880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b814d2ebbd8'
down_revision: Union[str, Sequence[str], None] = 'a49d6e32b01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('token_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtokens', 'token_type')
    # ### end Alembic commands ###
