"""add field and update realtionship

Revision ID: 4d7c838ea067
Revises: ca67bbe9394d
Create Date: 2025-07-20 13:56:37.458729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7c838ea067'
down_revision: Union[str, Sequence[str], None] = 'ca67bbe9394d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_refreshtokens_is_active'), 'refreshtokens', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_is_active'), table_name='refreshtokens')
    op.drop_column('refreshtokens', 'is_active')
    # ### end Alembic commands ###
