"""add field oauth

Revision ID: 385f4ed73ee8
Revises: 1b814d2ebbd8
Create Date: 2025-07-22 07:49:06.460215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385f4ed73ee8'
down_revision: Union[str, Sequence[str], None] = '1b814d2ebbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_oauth_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_user_oauth_id'), 'users', ['user_oauth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_oauth_id'), table_name='users')
    op.drop_column('users', 'user_oauth_id')
    # ### end Alembic commands ###
