"""add refresh token model

Revision ID: ca67bbe9394d
Revises: b13a56a18bb4
Create Date: 2025-07-20 13:52:45.318334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca67bbe9394d'
down_revision: Union[str, Sequence[str], None] = 'b13a56a18bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtokens',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtokens_access_token'), 'refreshtokens', ['access_token'], unique=False)
    op.create_index(op.f('ix_refreshtokens_refresh_token'), 'refreshtokens', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_refresh_token'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_access_token'), table_name='refreshtokens')
    op.drop_table('refreshtokens')
    # ### end Alembic commands ###
